"""Generate a PyInstaller version-info resource for an Open Orion executable.

Embeds real Windows version metadata (company, product, description, version,
original filename). CI runs this before each pyinstaller build and passes the
result via --version-file. Embedding this metadata is a Windows Defender /
SmartScreen hardening step: unsigned binaries with NO version info are far more
likely to be heuristic-flagged than ones with a coherent version resource.

Usage:
  python packaging/windows/gen_version_info.py orion 2.9.0  -> orion_version.txt
  python packaging/windows/gen_version_info.py orion-hud 2.9.0  -> orion-hud_version.txt
"""

from __future__ import annotations

import sys
from pathlib import Path


def render(name: str, version: str) -> str:
    # Accept "2.9.0" or "2.9.0.0"; pad to 4 parts for FixedFileInfo.
    parts = [int(p) for p in version.split(".")]
    parts = [*parts, 0, 0, 0][:4]
    a, b, c, d = parts
    description = {
        "orion": "Open Orion - autonomous terminal AI agent",
        "orion-hud": "Open Orion HUD - futuristic tkinter command deck",
    }.get(name, "Open Orion")
    return f"""# UTF-8
#
# Auto-generated by packaging/windows/gen_version_info.py - do not edit.

VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({a}, {b}, {c}, {d}),
    prodvers=({a}, {b}, {c}, {d}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          u'040904B0',
          [StringStruct(u'CompanyName', u'4matthedev'),
           StringStruct(u'FileDescription', u'{description}'),
           StringStruct(u'FileVersion', u'{a}.{b}.{c}.{d}'),
           StringStruct(u'InternalName', u'open-orion'),
           StringStruct(u'LegalCopyright', u'Copyright (c) 2025 4matthedev'),
           StringStruct(u'OriginalFilename', u'{name}.exe'),
           StringStruct(u'ProductName', u'Open Orion'),
           StringStruct(u'ProductVersion', u'{a}.{b}.{c}')]
        )
      ]
    ),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(__doc__)
        return 2
    name, version = argv[1], argv[2]
    out = Path(f"{name}_version.txt")
    out.write_text(render(name, version), encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
