; Open Orion — Windows installer (Inno Setup).
;
; Build with:
;   ISCC.exe packaging\windows\installer.iss /DAppVersion=2.9.0
;
; Expects dist\orion.exe (CLI) and dist\orion-hud.exe (HUD) built by
; PyInstaller with --icon=..\..\packaging\windows\open-orion.ico and a
; --version-file generated by packaging\windows\gen_version_info.py (running
; from packaging\windows, the icons below are resolved relative to this file).
;
; The installer optionally bootstraps the local runtime:
;   * downloads & silently installs Ollama if it isn't already present, and
;   * pulls the default model (qwen3.5:4b) so the first launch just works.

#ifndef AppVersion
  #define AppVersion "0.0.0"
#endif

#define AppName "Open Orion"
#define AppPublisher "4matthedev"
#define AppURL "https://github.com/4matthedev/open-orion"
#define ModelName "qwen3.5:4b"
#define OllamaUrl "https://ollama.com/download/OllamaSetup.exe"

[Setup]
AppId={{E6F4B08A-7C3D-4A1E-9B5F-5D0A4C7E13A2}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}
DefaultDirName={autopf}\Open Orion
DefaultGroupName=Open Orion
DisableProgramGroupPage=yes
OutputDir=..\..\dist-installer
OutputBaseFilename=OpenOrion-Setup-{#AppVersion}
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
SetupIconFile=open-orion.ico
UninstallDisplayIcon={app}\orion-hud.exe
WizardImageFile=wizard-banner.png
WizardSmallImageFile=wizard-small.png
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
PrivilegesRequired=admin
CloseApplications=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "ollama"; Description: "Install Ollama (local AI runtime) if not already installed"; GroupDescription: "Local AI runtime:"; Flags: checkedonce
Name: "model"; Description: "Download the {#ModelName} model (~2 GB) for instant first use"; GroupDescription: "Local AI runtime:"; Flags: checkedonce
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\..\dist\orion.exe";      DestDir: "{app}"; Flags: ignoreversion
Source: "..\..\dist\orion-hud.exe";  DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\Open Orion";           Filename: "{app}\orion-hud.exe"; WorkingDir: "{app}"; IconFilename: "{app}\orion-hud.exe"
Name: "{autoprograms}\Open Orion CLI";       Filename: "{app}\orion.exe"; WorkingDir: "{app}"; IconFilename: "{app}\orion.exe"
Name: "{autodesktop}\Open Orion";            Filename: "{app}\orion-hud.exe"; WorkingDir: "{app}"; Tasks: desktopicon

[Run]
; 1) Bootstrap the local AI runtime BEFORE launching the app. Each entry only
;    runs when its task is checked AND the condition is true.
Filename: "powershell.exe"; \
    Parameters: "-NoProfile -ExecutionPolicy Bypass -Command ""$u='{#OllamaUrl}'; $f=Join-Path $env:TEMP 'OllamaSetup.exe'; if (Test-Path $f) {{ Remove-Item $f -Force }}; [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest -UseBasicParsing -Uri $u -OutFile $f; $p=Start-Process -FilePath $f -ArgumentList '/SILENT' -Wait -PassThru; exit $p.ExitCode"""; \
    StatusMsg: "Installing Ollama (local AI runtime)..."; \
    Flags: runhidden waituntilterminated; \
    Check: WizardIsTaskSelected('ollama') and not IsOllamaInstalled()
Filename: "{code:GetOllamaExe}"; \
    Parameters: "pull {#ModelName}"; \
    StatusMsg: "Downloading the {#ModelName} model (this can take a while)..."; \
    Flags: runhidden waituntilterminated; \
    Check: WizardIsTaskSelected('model') and IsOllamaInstalled()

; 2) Launch the app.
Filename: "{app}\orion-hud.exe"; Description: "Launch Open Orion"; Flags: nowait postinstall skipifsilent

[Code]
{ Is Ollama already installed? Checked on PATH and the standard per-user path. }
function IsOllamaInstalled(): Boolean;
var
  Tmp: String;
begin
  Result := False;
  Tmp := AddBackslash(ExpandConstant('{localappdata}')) + 'Programs\Ollama\ollama.exe';
  if FileExists(Tmp) then
  begin
    Result := True;
    Exit;
  end;
  if RegValueExists(HKLM, 'SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\ollama.exe', '') then
    Result := True;
end;

{ Full path to the per-user Ollama launcher (PATH may not be refreshed in the
  installer process right after a fresh install). }
function GetOllamaExe(Param: String): String;
begin
  Result := AddBackslash(ExpandConstant('{localappdata}')) + 'Programs\Ollama\ollama.exe';
end;